image: tiangolo/docker-with-compose

before_script:
  - docker login -u gitlab-ci-token -p $CI_JON_TOKEN $CI_REGISTRY
  - pip install docker-auto-labels

stages:
  - test
  - build

tests:
  stage: test
  script:
    - sh ./scripts/test.sh
  tags:
    - build
    - test

